### ISSUE TITLE
Fail to connect sandbox websocket

### ISSUE THREAD

**Issue by markgk629** [airswap/developers#43]
By following the instructions on page [Quickstart](https://developers.airswap.io/#/getting-started/quickstart), got error on sandbox websocket connection.
```
> export PRIVATE_KEY=0x...
> export ENV=sandbox
> node app.js
WARNING: Multiple definitions for constructor
/airswap/developers/docs/tutorials/maker/node_modules/AirSwap.js/src/protocolMessaging/index.js:133
      throw new Error(event)
      ^

Error: [object Object]
    at WebSocket.socket.onerror.event (/airswap/developers/docs/tutorials/maker/node_modules/AirSwap.js/src/protocolMessaging/index.js:133:13)
    at WebSocket.onError (/airswap/developers/docs/tutorials/maker/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:189:13)
    at abortHandshake (/airswap/developers/docs/tutorials/maker/node_modules/ws/lib/websocket.js:649:15)
    at ClientRequest.req.on (/airswap/developers/docs/tutorials/maker/node_modules/ws/lib/websocket.js:542:5)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
```

But by exporting ENV to 'development' the connection works fine. Please advise.

**Comment by perich** [comment]
Sorry about this. We recently migrated away from using the `sandbox` environment. We will use only the `development` (rinkeby) and `production` (mainnet/homestead) from now on

https://github.com/airswap/developers/pull/44
